---
# Unix / WSL based packages

#  APT GPG keys for remote repositories
apt_gpg_keys:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg

#  APT remote repositories to track
apt_repositories:
  - "deb https://apt.kubernetes.io/ kubernetes-xenial main"

#  These should generally be kept in sync with osx/homebrew.yml packages
installed_packages:
  - coreutils
  - fish
  - git
  - npm
  - python
  - python3
  - tree
  - wget
  - awscli
  - rsync
  - jq
  - gnupg
  - direnv
  - apt-transport-https
  - kubectl
