---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - configs/osx-defaults.yml
    - configs/homebrew.yml
    # TODO: Re-enable with issue is fixed: https://github.com/mas-cli/mas/issues/107
#    - configs/mas.yml
    - configs/dotfiles.yml
    - configs/dock.yml

  roles:
    - role: geerlingguy.homebrew
    # TODO: Re-enable with issue is fixed: https://github.com/mas-cli/mas/issues/107
#    - role: geerlingguy.mas

  tasks:
    - include_tasks: tasks/osx-defaults.yml
    - include_tasks: tasks/pip.yml
    - include_tasks: tasks/dock.yml
    - include_tasks: tasks/dotfiles.yml
    # Become root user for editing through symlink on OSX (see https://stackoverflow.com/questions/33396807/ansible-lineinfile-give-an-error-with-etc-hosts)
    - include_tasks: ../tasks/fish-shell.yml
      become_user: root
